import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Linker from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS Example Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"/>
      </Head>
{/* Navbar */}
      <nav className="navbar navbar-expand-lg navbar-light bg-light mx-auto">
        <div className="container-fluid">
          <a className="navbar-brand" href="https://nextjs-example-yusufapriliyanto.vercel.app">Navbar</a>
            <ul className="navbar-nav ms-auto mb-2">
              <li className="nav-item">
                <a className="nav-link active ml-3" href="https://nextjs-example-yusufapriliyanto.vercel.app">Home</a>
              </li>
              <li className="nav-item">
                <a className="nav-link active ml-3" href="https://nextjs-example-yusufapriliyanto.vercel.app/diary_fiksi">Diary Fiksi</a>
              </li>
              <li className="nav-item">
                <a className="nav-link active ml-3" href="https://nextjs-example-yusufapriliyanto.vercel.app/konten_fiksi">Konten Fiksi</a>
              </li>
              <li className="nav-item">
                <a className="nav-link active ml-3" href="https://nextjs.org/docs/">Dokumentasi NextJS </a>
              </li>
              <li className="nav-item">
                <a className="nav-link active ml-3" href="https://nextjs-example-yusufapriliyanto.vercel.app/api/hello">Data Terkait Blog </a>
              </li>
            </ul>
        </div>
      </nav>
{/* Konten Diary*/}
      <h3>Diary p1 (26 Juli 2022)</h3>
      <h3>Oleh: Yusuf Apriliyanto</h3>
      <p>Di tengah keramaian, di tengah kerumunan. Aku disini menatap masa depan. Aku disini melihat mentari. Sinar sang surya, mewarnai masa mudaku. Ini adalah harapanku. Terang, seperti sinar sang surya. Menyinari dunia dengan kedamaian.</p>
      <p>Inilah harapanku. Terang, teranglah masa depanku. Seperti sinar mentari, seperti cahaya rembulan. Tetap bercahaya, apapun situasinya. Semoga, hari ini dan hari esok menjadi hari baik untukku. Semoga, mentari selalu ada untukku.</p>
      <p>Di tengah keramaian, aku disini menatap masa lalu. Masa laluku yang pernah suram, pernah pula terang. Dulu, inginku menjadi ulama. Namun apalah daya, tangan tak sampai, dan harapan itu sirna. Pernah pula harapku menjadi guru. Namun, itu bukanlah bakatku, bukan pula cahayaku.</p>
      <p>Kini, di tengah keramaian, aku belajar. Aku belajar membangun argumen. Aku belajar menulis, menulis diatas langit. Tulisan yang tak terlihat, namun bisa dibaca. Aku belajar tentang paper, tesis, disertasi, skripsi, dan jurnal ilmiah.</p>
      <p>Sampai pada akhirnya, aku sampai pada sebuah titik. Titik terang dari segalanya. Aku menemukan aljabar, fungsi, integral, limit, dan sekumpulan simbol. Itulah Matematika, cahaya kedua yang aku temukan setelah menemukan Pemograman</p>
      <p>Tapi sebelum cahaya kedua, aku menemukan banyak hal. Sebanyak tetesan hujan, sebanyak tetesan embun. Juga dengan sekumpulan simbol, dan sekumpulan istilah.</p>
      <p>Namun, aku mau cahaya yang lebih banyak. Aku mau seribu cahaya lagi. Atau, satu cahaya yang sebesar sang mentari.</p>
      <p>Akhir kata, apakah ada diantara pembaca yang bernama Cahaya, Surya, Mentari, dan Ilmiah? Jika ada, Anda menjadi inspirasi saya hari ini.</p>
    </div>
  )
}
